import os
import asyncio
from playwright.async_api import Playwright, async_playwright, expect


async def main():
    async with async_playwright() as p:
        for browser_type in [p.chromium, p.firefox, p.webkit]:
            browser = await browser_type.launch(headless=False)
            page = await browser.new_page()
            await page.goto("https://github.com/")
            await page.get_by_role("link", name="Sign in").click()

            username = os.environ.get('GITHUB_USERNAME')
            password = os.environ.get('GITHUB_PASSWORD')
            repo_name = os.environ.get('GITHUB_REPO_NAME')

            await page.get_by_label("Username or email address").click()
            await page.get_by_label("Username or email address").fill(username)
            await page.get_by_label("Password").click()
            await page.get_by_label("Password").fill(password)
            await page.get_by_role("button", name="Sign in").click()
            await page.get_by_role("heading", name="Top Repositories New").get_by_role("link", name="New").click()
            await page.get_by_label("Repository name").click()
            await page.get_by_label("Repository name").fill(repo_name)
            await page.get_by_label("Add a README file").check()
            await page.get_by_role("button", name="Create repository").click()
            await page.get_by_role("button", name="Add file").click()
            await page.get_by_role("button", name="Create new file").click()
            await page.locator("#code-editor pre").click()
            await page.get_by_placeholder("Create hello_world.py").click()
            await page.get_by_placeholder("Create hello_world.py").fill("adding hello world python script")
            await page.get_by_role("button", name="Commit new file").click()
            await page.get_by_role("link", name="Issues Issues").click()
            await page.get_by_role("button", name="New issue").click()
            await page.get_by_placeholder("Title").fill("Add goodbye to script")
            await page.get_by_placeholder("Leave a comment").click()
            await page.get_by_placeholder("Leave a comment").fill("This script is too basic and should allow for a user to select hello and print hello world and also the same thing for goodbye. This way the user has two options that do two different things.")
            await page.get_by_role("button", name="Submit new issue").click()
            await page.get_by_role("link", name="Actions Actions").click()
            await page.get_by_role("link", name="set up a workflow yourself").click()
            await page.get_by_placeholder("Name your file…").click()
            await page.get_by_placeholder("Name your file…").click()
            await page.get_by_placeholder("Name your file…").fill("hello.yaml")
            await page.locator("#code-editor pre").click()
            await page.locator("#code-editor").press("Enter")
            await page.get_by_text("1name: hello2").press("Enter")
            await page.get_by_text("1name: hello2on: push3").press("Enter")
            await page.get_by_text("1name: hello2on: push3jobs:4").press("Tab")
            await page.get_by_text("1name: hello2on: push3jobs:4").press("Enter")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5").press("Tab")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5").press("Enter")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5 runs-on: ubuntu-latest6").press("Enter")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5 runs-on: ubuntu-latest6 steps:7").press("Tab")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5 runs-on: ubuntu-latest6 steps:7").press("Enter")
            await page.get_by_text("1name: hello2on: push3jobs:4 my-job:5 runs-on: ubuntu-latest6 steps:7 - name: my").press("Tab")
            await page.get_by_text("Start commit").click()
            await page.get_by_placeholder("Create hello.yaml").click()
            await page.get_by_placeholder("Create hello.yaml").fill("adding github action")
            await page.get_by_role("button", name="Commit new file").click()
            await page.get_by_role("link", name="Settings Settings").click()
            await page.get_by_role("link", name="Branches").click()
            await page.get_by_role("link", name="Add branch protection rule").click()
            await page.get_by_label("Lock branch").check()
            await page.get_by_label("Branch name pattern").click()
            await page.get_by_label("Branch name pattern").fill("main")
            await page.get_by_text("Create").click()
            await page.get_by_role("link", name="Code Code").click()
            await page.get_by_role("button", name="View profile and more").click()
            await page.get_by_role("menuitem", name="Sign out").click()
            await context.close()
            await browser.close()

asyncio.run(main())
